vente/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include,re_path
from gestion.views import home,CommandeCreateView,recup,search
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home,name="home"),
    path('commande/<int:id_article>', CommandeCreateView.as_view(), name='commande'),
    path('afficher/<int:id_commande>/', recup, name='afficher'),
    path("auth/",include("app_auth.urls")),
    path("my-admin/",include("app_admin.urls")),
    path("article/recherche",search,name="search"),# tu vas dans article tu va cliquer sur recherche et on va appeler la fonctions search depuis views
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT} ), # pour les fichiers de MEDIA
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT} ), # pour les fichiers de STATIC
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) # obligatoire 

gestion/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import RegexValidator
# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Article(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    nom_category=models.ForeignKey(Category,on_delete=models.CASCADE,null=True)
    nom = models.CharField(max_length=100)
    description = models.TextField()
    prix = models.DecimalField(max_digits=8, decimal_places=2)
    photo1 = models.ImageField(null=True,blank=True)
    photo2 = models.ImageField(null=True,blank=True)
    exemplaires_disponibles = models.IntegerField(null=True, blank=True)
    
    def nombre_exemplaires_epuises(self):
        epuisee=self.commande_set.filter(statut='livre').count()
        return epuisee
    

    def nombre_exemplaires_restants(self):
         
        restante=self.exemplaires_disponibles - self.nombre_exemplaires_epuises()
        return restante
    

    def __str__(self):
        return self.nom
    def get_absolute_url(self):
        return reverse("commande") 
    
    def get_absolute_url(self):
        return reverse("my-article") 

class Commande(models.Model):
    TAILLE_CHOICES = [
        ('X', 'X'),
        ('XL', 'XL'),
        ('XXL', 'XXL'),
        ('M', 'M'),
    ]
    
    STATUT_CHOICES = [
        ('en_cours', 'En cours'),
        ('livre', 'Livrée'),
    ]
    
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    nom_client = models.CharField(max_length=100)
    numero_client = models.CharField(
        max_length=20,
        validators=[
            RegexValidator(
                regex=r'^\d{10}$',  # Format: 10 chiffres
            )
        ]
    )
    quantite = models.PositiveIntegerField()
    taille = models.CharField(max_length=3, choices=TAILLE_CHOICES, default='null')
    statut = models.CharField(max_length=10, choices=STATUT_CHOICES, default='en_cours')
    date_commande = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Commande de {self.quantite} {self.article.nom} ({self.get_taille_display()}) par {self.nom_client}"



    

gestion/forms.py
from django import forms
from .models import Commande,Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["nom", "description", "prix", "photo1", "photo2"]
        labels = {
            "nom": "Nom",
            "description": "Description",
            "prix": "Prix",
            "photo1": "Photo 1",
            "photo2": "Photo 2",
           
        }
        widgets = {
            "nom": forms.TextInput(attrs={"class": "form-control"}),
            "description": forms.Textarea(attrs={"class": "form-control"}),
            "prix": forms.NumberInput(attrs={"class": "form-control"}),
            "photo1": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "photo2": forms.ClearableFileInput(attrs={"class": "form-control"}),
           
        }





class CommandeForm(forms.ModelForm):
    class Meta:
        model = Commande
        fields = ['nom_client', 'numero_client', 'quantite','taille']
        labels = {
            'nom_client': 'Nom',
            'numero_client': 'Numéro de téléphone',
            'quantite': 'Quantité',
            'taille': 'Taille',
           

            
            
        }

gestion/views.py
from django.shortcuts import render, redirect
import os

from .forms import CommandeForm
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .models import Article, Commande
from django.contrib import messages

# Create your views here.
def home(request): # parametre request obligatoire qui va permettre les requettes http
    list_article=Article.objects.all() # tu recupere tout les objets de la classe article pour mettre dans list_article
    context={"liste_articles":list_article}

    return render(request,"index.html",context)# veut dire tu m'envoi un templates appellé index.html
    # je vais dans mon dossier charo pour creer un dossier templates
    # render permet de rendre le fichier html au user et tu vas le rendre avec context


def search(request):
    #GET={"article":"cafe"} c'est ce qui ce passe dans la ligne juste apres
    query=request.GET["article"]
    liste_article=Article.objects.filter(nom__icontains=query) # tu vas selectioner tout les objets dont le titre est egale à qruery
    return render(request,"search.html",{"liste_articles":liste_article})
    # les ypes de requettes : SELECT *FROM Article where titre LIKE %'query'% veut dit que si il ya des mot dans la demande de l'utilisateur et que notre titre est dedans on envoi la requettes







def recup(request, id_commande):
    commande = Commande.objects.get(id=id_commande)
    article = commande.article
    nom_client = commande.nom_client
    num_client = commande.numero_client
    quantite = commande.quantite
    
    
    context = {
        "nom_client": nom_client,
        "nom_article": article.nom,
        "quantite": quantite,
        "numero_client": num_client,
        "total": (article.prix * quantite) 
    }

       

    


    


    return render(request, "effectuer.html", context)




class CommandeCreateView(CreateView):
    model = Commande
    form_class = CommandeForm
    template_name = 'comande.html'
    success_url = reverse_lazy("afficher", kwargs={'id_commande': None})

    def get_success_url(self):
        return reverse_lazy("afficher", kwargs={'id_commande': self.object.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article_id = self.kwargs['id_article']
        article = Article.objects.get(id=article_id)
        context['article'] = article
        return context

    def form_valid(self, form):
        numero_client = form.cleaned_data['numero_client']
        
        if len(numero_client) == 10:
            article_id = self.kwargs['id_article']
            article = Article.objects.get(id=article_id)
            form.instance.article = article
            return super(CommandeCreateView, self).form_valid(form)
        else:
            messages.error(self.request, "Numéro incorrect. Veuillez entrer un numéro de 10 chiffres.")
            
            return super(CommandeCreateView, self).form_valid(form)

gestion/templates/_footer.html
<!-- Footer -->
<footer class="page-footer font-small stylish-color-dark pt-4">

    <!-- Footer Links -->
    <div class="container text-center text-md-left">
  
      <!-- Grid row -->
      <div class="row">
  
        <!-- Grid column -->
        <div class="col-md-4 mx-auto">
  
          <!-- Content -->
          <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Nous avons vos articles de <br> premier choix ,la qualite est notre priorite</h5>
          <p> </p>
  
        </div>
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none">
  
        <!-- Grid column -->
       
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none">
  
        <!-- Grid column -->
        
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none">
  
        <!-- Grid column -->
        
        <!-- Grid column -->
  
      </div>
      <!-- Grid row -->
  
    </div>
    <!-- Footer Links -->
  
    <hr>
  
    <!-- Call to action -->
    <ul class="list-unstyled list-inline text-center py-2">
      <li class="list-inline-item">
        <h5 class="mb-1">Ouvert de 08h-18h</h5>
      </li>
      <li class="list-inline-item">
        <h5 class="btn btn-danger btn-rounded">Situe à angre </h5>
      </li>
    </ul>
    <!-- Call to action -->
  
    <hr>
  
    <!-- Social buttons -->
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
        <a class="btn-floating btn-fb mx-1">
          <i class="fab fa-facebook-f"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-tw mx-1">
          <i class="fab fa-twitter"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-gplus mx-1">
          <i class="fab fa-google-plus-g"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-li mx-1">
          <i class="fab fa-linkedin-in"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-dribbble mx-1">
          <i class="fab fa-dribbble"> </i>
        </a>
      </li>
    </ul>
    <!-- Social buttons -->
  
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2023 Copyright:
      <a href="/"> Sergetanoh.com</a>
    </div>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->



 

gestion/templates/_nav.html
{% load static %}

<nav class="navbar navbar-dark default-color navbar-expand-md justify-content-between">
  <a class="navbar-brand" href="{% url 'home' %}">
    <img src="{% static 'img/logoe.jpg' %}" alt="Logo" style="width: 50px;">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="#contact">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'my-article' %}">Admin</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">À propos de nous</a>
      </li>
    </ul>
    <form class="form-inline my-1" action="{% url 'search' %}">
      <div class="md-form form-sm my-0">
        {% if user.is_authenticated %}
        <a href="{% url 'logout1' %}" class="btn btn-primary">Déconnexion</a>
        {% else %}
        <a href="{% url 'login-blog' %}" class="btn btn-primary">Connexion</a>
        {% endif %}
        <input class="form-control form-control-sm mr-sm-2 mb-0" type="text" placeholder="Recherche" aria-label="Search" name="article">
      </div>
    </form>
  </div>
</nav>

gestion/templates/base.html
<!DOCTYPE html>
{%load static %} <!-- est une fonction de django qui permet de modifier le front -->
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Vos Habits  {% endblock %} </title>
    <!-- MDB icon -->
    <link rel="icon" href="{ %static 'img/logoe.jpeg'%}" type="image/x-icon">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    
        <!-- Autres balises meta et liens -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css">
      
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <!-- Your custom styles (optional) -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
        
    
        
      

</head>

<body>
{% include '_nav.html' %}
{% block content %}
 <!-- toutes mes donnes dont j'aurai a afficher hertierons de base.html et se situerons dans block -->
{% endblock %}





    <!-- jQuery -->
    <script type="text/javascript" src="{%static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js'%}"></script>
    <!-- Your custom scripts (optional) -->
    <script type="text/javascript"></script>
    {% block scripts %} 
    
    {% endblock %}
</body>

</html>

gestion/templates/comande.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
  /* Style pour centrer la carte */
  .card-container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    backdrop-filter: blur(5px); /* Applique un flou à l'arrière-plan */
  }

  .card {
    width: 400px; /* Ajustez la largeur de la card selon vos besoins */
  }

  /* Ajoutez de l'espace entre les éléments à l'intérieur de la carte */
  .card-body {
    padding: 20px; /* Ajustez l'espacement intérieur selon vos besoins */
  }

  .form-label {
    margin-bottom: 10px; /* Espacement entre les étiquettes des champs */
  }

  .btn {
    margin-top: 10px; /* Espacement entre les boutons */
  }
</style>

<div class="card-container">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title text-center">Formulaire de commande pour l'article "{{ article.nom }}"</h5>
      <form class="row g-3" method="post" novalidate>
        {% csrf_token %}
        <div class="col-12 text-center">
          <label for="id_nom_client" class="form-label">Nom</label><br>
          {{ form.nom_client }}
        </div>
        <div class="col-12 text-center">
          <label for="id_numero_client" class="form-label">Numéro de téléphone</label><br>
          {% if form.numero_client.errors %}
            {% for error in form.numero_client.errors %}
              <div class="">
                <small class="text-danger">Numero incorect</small>
              </div>
            {% endfor %}
          {% endif %}
          {{ form.numero_client }}
        </div>
        <div class="col-12 text-center">
          <label for="id_quantite" class="form-label">Quantité</label><br>
          {{ form.quantite }}
        </div>
        <div class="col-12 text-center">
          <label for="id_taille" class="form-label">Taille</label><br>
          {{ form.taille }}
        </div>
        <div class="col-12 text-center">
          <button type="submit" class="btn btn-primary">Valider</button>
          <button type="reset" class="btn btn-secondary">Réinitialiser</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

gestion/templates/effectuer.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Confirmation de commande</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
body {
	font-family: 'Varela Round', sans-serif;
}
.modal-confirm {		
	color: #636363;
	width: 325px;
	font-size: 14px;
}
.modal-confirm .modal-content {
	padding: 20px;
	border-radius: 5px;
	border: none;
}
.modal-confirm .modal-header {
	border-bottom: none;   
	position: relative;
}
.modal-confirm h4 {
	text-align: center;
	font-size: 26px;
	margin: 30px 0 -15px;
}
.modal-confirm .form-control, .modal-confirm .btn {
	min-height: 40px;
	border-radius: 3px; 
}
.modal-confirm .close {
	position: absolute;
	top: -5px;
	right: -5px;
}	
.modal-confirm .modal-footer {
	border: none;
	text-align: center;
	border-radius: 5px;
	font-size: 13px;
}	
.modal-confirm .icon-box {
	color: #fff;		
	position: absolute;
	margin: 0 auto;
	left: 0;
	right: 0;
	top: -70px;
	width: 95px;
	height: 95px;
	border-radius: 50%;
	z-index: 9;
	background: #82ce34;
	padding: 15px;
	text-align: center;
	box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.1);
}
.modal-confirm .icon-box i {
	font-size: 58px;
	position: relative;
	top: 3px;
}
.modal-confirm.modal-dialog {
	margin-top: 80px;
}
.modal-confirm .btn {
	color: #fff;
	border-radius: 4px;
	background: #82ce34;
	text-decoration: none;
	transition: all 0.4s;
	line-height: normal;
	border: none;
}
.modal-confirm .btn:hover, .modal-confirm .btn:focus {
	background: #6fb32b;
	outline: none;
}
.trigger-btn {
	display: none; /* Masquer le lien */
}
</style>
<script>
$(document).ready(function(){
  $('#myModal').modal('show'); // Ouvrir le modal automatiquement
});
</script>
</head>
<body>


<!-- Modal HTML -->
<div id="myModal" class="modal fade">
	<div class="modal-dialog modal-confirm">
		<div class="modal-content">
			<div class="modal-header">
				<div class="icon-box">
					<i class="material-icons">&#xE876;</i>
				</div>				
				<h4 class="modal-title w-100">Commande effectuée</h4>	
			</div>
			<div class="modal-body">
				<p class="text-center">{{ nom_client }}, votre commande de {{ quantite }} exemplaire(s) de l'article "{{ nom_article }}" a été prise en compte le total est {{total}} FCFA.<br> Vous allez recevoir un appel de notre service client dans les minutes qui suivent.</p>
			</div>
			<div class="modal-footer">
				<a href="{% url 'home' %}" class="btn btn-success btn-block">OK</a>

			</div>
		</div>
	</div>
</div>     
</body>
</html>

gestion/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <h1 class="text-center mt-3">Découvrez nos habits drip on drip </h1>

  <div class="row mt-4">
    <!-- Vidéo YouTube -->
    <div class="col-12 mb-4">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/B5wX0S1p-Uc?si=fRGhl8TJ21oCmh3X" allowfullscreen></iframe>
      </div>
    </div>

    <!-- Produits -->
    {% for article in liste_articles %}
    <div class="col-12 col-md-6 col-lg-3 mb-4">
      <div class="card h-100">
        <div id="carouselExample{{ article.id }}" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{{ article.photo1.url }}" class="d-block w-100" alt="Photo 1">
            </div>
            <div class="carousel-item">
              <img src="{{ article.photo2.url }}" class="d-block w-100" alt="Photo 2">
            </div>
            <div class="carousel-item">
              <img src="{{ article.photo3.url }}" class="d-block w-100" alt="Photo 3">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample{{ article.id }}" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExample{{ article.id }}" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <div class="card-body">
          <h5 class="card-title">{{ article.nom }}</a></h5>
          <p class="card-text">{{ article.description }}</p>
          <p class="card-text">Prix : {{ article.prix }} FCFA</p>
          <a href="{% url 'commande' article.id %}" class="btn btn-primary">Commander</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<footer id="contact" class="footer mt-auto py-3 bg-dark text-white">
  <div class="container text-center">
    <span class="text-muted">© Contact : 0141752812.</span>
    <span class="text-muted">© 2024 Simshop. Tous droits réservés.</span>
    <div class="social-links mt-3">
      <a href="https://www.facebook.com/profile.php?id=100063612234103&mibextid=LQQJ4d" class="text-white me-3">
        <i class="fab fa-facebook-f"></i>
      </a>
      
      <a href="https://wa.me/0141752812" class="text-white me-3">
        <i class="fab fa-whatsapp"></i>
      </a>

      <a href="https://www.instagram.com/simshop_?igsh=MWJ4bHhhenR0aTU5ZQ==" class="text-white me-3">
        <i class="fab fa-instagram"></i>
      </a>
      
    </div>
  </div>
</footer>



<!-- JavaScript pour améliorer l'interaction -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script>
  $(document).ready(function() {
    // Ajoute une classe de style au survol des cartes
    $('.card').hover(
      function() {
        $(this).addClass('shadow-lg').css('cursor', 'pointer');
      },
      function() {
        $(this).removeClass('shadow-lg');
      }
    );

    // Ajoute un zoom sur les images au survol
    $('.carousel-item img').hover(
      function() {
        $(this).addClass('img-zoom');
      },
      function() {
        $(this).removeClass('img-zoom');
      }
    );
  });
</script>
{% endblock %}

gestion/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1 class="text-center mt-3">Liste de recherches</h1>
<div class="container">
  <div class="row">
    {% for article in liste_articles %}
    <div class="col-12 col-md-6 col-lg-3 col-xl-3 mb-2">
      <div class="card p-2">
        <div id="carouselExample{{ article.id }}" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{{ article.photo1.url }}" class="d-block w-100" alt="photo1">
            </div>
            <div class="carousel-item">
              <img src="{{ article.photo2.url }}" class="d-block w-100" alt="photo2">
            </div>
            <div class="carousel-item">
              <img src="{{ article.photo3.url }}" class="d-block w-100" alt="photo3">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample{{ article.id }}" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExample{{ article.id }}" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <div class="card-body" style="height: 230px;">
          <h5 class="card-title"><a href="">{{ article.nom }}</a></h5>
          <p class="card-text">{{ article.description  }}</p>
          <p class="card-text">Prix {{article.prix }}</p>
          <a href="{% url 'commande' article.id %}" class="btn btn-primary">Commander</a>

        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<!-- Ajoute le code JavaScript ici -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script>
  $(document).ready(function() {
    $('.card').hover(
      function() {
        $(this).addClass('shadow-lg').css('cursor', 'pointer');
      },
      function() {
        $(this).removeClass('shadow-lg');
      }
    );
  });
</script>
{% endblock %}