app_admin/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('',dashboard,name='dashboard'),
    path('my-article',user_article,name='my-article'),
    path('ajouter-article',Add_article.as_view(),name='ajout-article'),
    path('modifier-article/<int:pk>',update_article.as_view(),name='modif'),
    path('suprimer-article/<int:pk>',delete_article.as_view(),name='suprimer'),
    path('suprimer-commande/<int:pk>',delete_commande.as_view(),name='delete'),
    path('search',search,name='search1'),

]

vente/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include,re_path
from gestion.views import home,CommandeCreateView,recup,search
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home,name="home"),
    path('commande/<int:id_article>', CommandeCreateView.as_view(), name='commande'),
    path('afficher/<int:id_commande>/', recup, name='afficher'),
    path("auth/",include("app_auth.urls")),
    path("my-admin/",include("app_admin.urls")),
    path("article/recherche",search,name="search"),# tu vas dans article tu va cliquer sur recherche et on va appeler la fonctions search depuis views
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT} ), # pour les fichiers de MEDIA
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT} ), # pour les fichiers de STATIC
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) # obligatoire 

app_admin/models.py
from django.db import models

# Create your models here.

gestion/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import RegexValidator
# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Article(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    nom_category=models.ForeignKey(Category,on_delete=models.CASCADE,null=True)
    nom = models.CharField(max_length=100)
    description = models.TextField()
    prix = models.DecimalField(max_digits=8, decimal_places=2)
    photo1 = models.ImageField(null=True,blank=True)
    photo2 = models.ImageField(null=True,blank=True)
    exemplaires_disponibles = models.IntegerField(null=True, blank=True)
    
    def nombre_exemplaires_epuises(self):
        epuisee=self.commande_set.filter(statut='livre').count()
        return epuisee
    

    def nombre_exemplaires_restants(self):
         
        restante=self.exemplaires_disponibles - self.nombre_exemplaires_epuises()
        return restante
    

    def __str__(self):
        return self.nom
    def get_absolute_url(self):
        return reverse("commande") 
    
    def get_absolute_url(self):
        return reverse("my-article") 

class Commande(models.Model):
    TAILLE_CHOICES = [
        ('X', 'X'),
        ('XL', 'XL'),
        ('XXL', 'XXL'),
        ('M', 'M'),
    ]
    
    STATUT_CHOICES = [
        ('en_cours', 'En cours'),
        ('livre', 'Livrée'),
    ]
    
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    nom_client = models.CharField(max_length=100)
    numero_client = models.CharField(
        max_length=20,
        validators=[
            RegexValidator(
                regex=r'^\d{10}$',  # Format: 10 chiffres
            )
        ]
    )
    quantite = models.PositiveIntegerField()
    taille = models.CharField(max_length=3, choices=TAILLE_CHOICES, default='null')
    statut = models.CharField(max_length=10, choices=STATUT_CHOICES, default='en_cours')
    date_commande = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Commande de {self.quantite} {self.article.nom} ({self.get_taille_display()}) par {self.nom_client}"



    

app_admin/views.py
from django.shortcuts import render,redirect
from gestion.models import Article,Commande
from django.views.generic.edit import UpdateView,DeleteView,CreateView
from gestion.forms import ArticleForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseBadRequest


def dashboard(request):
    return render (request,'db.html')

def search(request):
    #GET={"article":"cafe"} c'est ce qui ce passe dans la ligne juste apres
    query=request.GET["commande"]
    liste_commandes=Commande.objects.filter(date_commande__icontains=query) # tu vas selectioner tout les objets dont le titre est egale à qruery
    return render(request,"voir-article.html",{"liste_commandes":liste_commandes})
    # les ypes de requettes : SELECT *FROM Article where titre LIKE %'query'% veut dit que si il ya des mot dans la demande de l'utilisateur et que notre titre est dedans on envoi la requettes


def user_article(request):
    if not request.user.is_superuser: # si l'utilisateur n'est pas connecte et veut acceder a l'espace admin on refuse
        return redirect('login-blog')
    list_article=Article.objects.all()
    Comande = Commande.objects.all()
    context={'list_articles':list_article,'liste_commande':Comande}
    return render(request,'my-article.html',context)


class Add_article(LoginRequiredMixin, CreateView):
    model = Article
    form_class = ArticleForm
    template_name = "add-article.html"
    success_url = "my-article"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class update_article(LoginRequiredMixin,UpdateView):
    model=Article
    form_class=ArticleForm
    template_name="app_admin/article_form.html"

    
class delete_article(LoginRequiredMixin,DeleteView):
    model=Article
    success_url='../my-article'
    template_name="app_admin/article_confirm_delete.html"


class delete_commande(LoginRequiredMixin,DeleteView):
    model=Commande
    success_url='../my-article'
    template_name="app_admin/commande_confirm_delete.html"
    
    

app_admin/templates/add-article.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
<style>
  /* Style pour centrer la carte */
  .card-container {
    display: flex;
    justify-content: center;
    align-items: center;
    backdrop-filter: blur(5px); /* Applique un flou à l'arrière-plan */
  }

  .card {
    width: 320px; /* Ajustez la largeur de la card selon vos besoins */
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
  }

  /* Style pour les champs de formulaire */
  .form-label {
    font-weight: bold;
  }

  .form-control {
    margin-bottom: 10px;
  }

  /* Style pour les boutons */
  .btn-primary {
    width: 100%;
  }
</style>

<div class="card-container">
  <div class="card mt-2">
    <div class="card-body">
      <form class="row g-3" method="post" enctype="multipart/form-data">
        {% csrf_token %}
          
        <div class="col-12">
          <label for="id_nom" class="form-label">Nom Article</label>
          {{ form.nom }}
        </div>

        <div class="col-12">
          <label for="id_description" class="form-label">Description</label>
          {{ form.description }}
        </div>

        <div class="col-12">
          <label for="id_prix" class="form-label">Prix</label>
          {{ form.prix }}
        </div>

        <div class="col-12">
          <label for="id_photo1" class="form-label">Photo 1</label>
          {{ form.photo1 }}
        </div>

        <div class="col-12">
          <label for="id_photo2" class="form-label">Photo 2</label>
          {{ form.photo2 }}
        </div>

        <div class="col-12">
          <label for="id_photo3" class="form-label">Photo 3</label>
          {{ form.photo3 }}
        </div>

        <div class="col-12">
          <button type="submit" class="btn btn-primary">Valider</button>
          <button type="reset" class="btn btn-secondary">Réinitialiser</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

app_admin/templates/db.html
{% extends 'partials/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <h2>Tableau de bord </h2>
    </div>
</div>
{% endblock %} 

app_admin/templates/my-article.html
{% extends 'partials/base.html' %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            
            <a class="btn btn-secondary float-right" href="{% url 'ajout-article' %}"><i class="fas fa-plus"></i> Ajouter article</a>
        </div>
        

        </div>
    </div>
</div>







<body>

  <!-- ======= Header ======= -->
  

  <!-- ======= Sidebar ======= -->
 

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Dashboard</h1>
      <nav>
        <ol class="breadcrumb">
          
          
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
      <div class="row">

        <!-- Left side columns -->
        <div class="col-lg-8">
          <div class="row">

            <!-- Sales Card -->
            <div class="col-xxl-4 col-md-6">
              <div class="card info-card sales-card">

                
                
              </div>
            </div><!-- End Sales Card -->

            <!-- Revenue Card -->
            <div class="col-xxl-4 col-md-6">
              <div class="card info-card revenue-card">

                

                

              </div>
            </div><!-- End Revenue Card -->

            <!-- Customers Card -->
           

            <!-- Reports -->
            

                

                <div class="card-body">
                 

                  <!-- Line Chart -->
                  <div id="reportsChart"></div>

                  <script>
                    document.addEventListener("DOMContentLoaded", () => {
                      new ApexCharts(document.querySelector("#reportsChart"), {
                        series: [{
                          name: 'Sales',
                          data: [31, 40, 28, 51, 42, 82, 56],
                        }, {
                          name: 'Revenue',
                          data: [11, 32, 45, 32, 34, 52, 41]
                        }, {
                          name: 'Customers',
                          data: [15, 11, 32, 18, 9, 24, 11]
                        }],
                        chart: {
                          height: 350,
                          type: 'area',
                          toolbar: {
                            show: false
                          },
                        },
                        markers: {
                          size: 4
                        },
                        colors: ['#4154f1', '#2eca6a', '#ff771d'],
                        fill: {
                          type: "gradient",
                          gradient: {
                            shadeIntensity: 1,
                            opacityFrom: 0.3,
                            opacityTo: 0.4,
                            stops: [0, 90, 100]
                          }
                        },
                        dataLabels: {
                          enabled: false
                        },
                        stroke: {
                          curve: 'smooth',
                          width: 2
                        },
                        xaxis: {
                          type: 'datetime',
                          categories: ["2018-09-19T00:00:00.000Z", "2018-09-19T01:30:00.000Z", "2018-09-19T02:30:00.000Z", "2018-09-19T03:30:00.000Z", "2018-09-19T04:30:00.000Z", "2018-09-19T05:30:00.000Z", "2018-09-19T06:30:00.000Z"]
                        },
                        tooltip: {
                          x: {
                            format: 'dd/MM/yy HH:mm'
                          },
                        }
                      }).render();
                    });
                  </script>
                  <!-- End Line Chart -->

                </div>

              

            <!-- Recent Sales -->
            <div class="col-12">
              <div class="card recent-sales overflow-auto">

                

                <div class="card-body">
                  <h5 class="card-title">Commandes <span>| client</span></h5>
                  <div class="row">
                    <div class="col-6 ">
                      <div class="input-group">
                        <form class="form-inline my-1" action="{% url 'search1' %}">
                          <div class="md-form form-sm my-0">
                            <input class="form-control form-control-sm mr-sm-2 mb-0" type="text" placeholder="Recherche" aria-label="Search" name="commande">
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>

                  <table class="table table-borderless datatable">
                    <thead>
                      <tr>
                        <th scope="col">nom client</th>
                        <th scope="col">nom article</th>
                        <th scope="col">quantite</th>
                        <th scope="col">taille</th>
                        <th scope="col">Prix</th>
                        <th>date de commande </th>
                        
                        <th class="float-right h6" style="margin-right: 55px;">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      
                        {%for commande in liste_commande %}
                        
                      <tr>
                        <th scope="row"><a href="#">{{commande.nom_client}}</a></th>
                        <td>{{commande.article.nom}}</td>
                        <td>{{commande.quantite}}</td>
                        <td>{{commande.taille}}</td>
                        <td>{{commande.article.prix}} FCFA</td>
                        <td>{{commande.date_commande}}</td>
                        
                        <td><a href="{%url 'delete' commande.id %}" class="btn btn-danger float-right btn-sm "style="right: 10px;"><i class="fas fa-trash"></i></a></td>
                      </tr>
                      {% endfor %}
                      
                    </tbody>
                  </table>

                </div>

              </div>
            </div><!-- End Recent Sales -->

            <!-- Top Selling -->
            

          </div>
        </div><!-- End Left side columns -->

        <!-- Right side columns -->
        <div class="col-lg-4">

          <!-- Recent Activity -->
          <div class="card mt-5">
            <div class="filter">
              <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
              
            </div>

            <div class="card-body">
              <h5 class="card-title">Article <span>|disponible </span></h5>

              <table class="table table-borderless datatable">
                <thead>
                  <tr>
                    
                    <th scope="col">nom article</th>
                    
                    <th scope="col">Prix</th>
                    <th class="float-right h6" style="margin-right: 55px;">Action</th>
                  </tr>
                </thead>
                <tbody>
                  
                    {%for article in list_articles %}
                  <tr>
                    <th scope="row"><a href="#">{{article.nom}}</a></th>
                    <td>{{article.prix}}</td>
                    <td>
                        <a href="{%url 'modif' article.id %}" class="btn btn-info float-right btn-sm " ><i class="fas fa-edit"></i></a>
                        <a href="{%url 'suprimer' article.id %}" class="btn btn-danger float-right btn-sm "style="right: 10px;"><i class="fas fa-trash"></i></a>
                    </td>
                  </tr>
                  {% endfor %}
                  
                </tbody>
              </table>

            </div>
          </div><!-- End Recent Activity -->

          <!-- Budget Report -->
          

              <script>
                document.addEventListener("DOMContentLoaded", () => {
                  var budgetChart = echarts.init(document.querySelector("#budgetChart")).setOption({
                    legend: {
                      data: ['Allocated Budget', 'Actual Spending']
                    },
                    radar: {
                      // shape: 'circle',
                      indicator: [{
                          name: 'Sales',
                          max: 6500
                        },
                        {
                          name: 'Administration',
                          max: 16000
                        },
                        {
                          name: 'Information Technology',
                          max: 30000
                        },
                        {
                          name: 'Customer Support',
                          max: 38000
                        },
                        {
                          name: 'Development',
                          max: 52000
                        },
                        {
                          name: 'Marketing',
                          max: 25000
                        }
                      ]
                    },
                    series: [{
                      name: 'Budget vs spending',
                      type: 'radar',
                      data: [{
                          value: [4200, 3000, 20000, 35000, 50000, 18000],
                          name: 'Allocated Budget'
                        },
                        {
                          value: [5000, 14000, 28000, 26000, 42000, 21000],
                          name: 'Actual Spending'
                        }
                      ]
                    }]
                  });
                });
              </script>

            </div>
          </div><!-- End Budget Report -->

          <!-- Website Traffic -->
          

            

              <script>
                document.addEventListener("DOMContentLoaded", () => {
                  echarts.init(document.querySelector("#trafficChart")).setOption({
                    tooltip: {
                      trigger: 'item'
                    },
                    legend: {
                      top: '5%',
                      left: 'center'
                    },
                    series: [{
                      name: 'Access From',
                      type: 'pie',
                      radius: ['40%', '70%'],
                      avoidLabelOverlap: false,
                      label: {
                        show: false,
                        position: 'center'
                      },
                      emphasis: {
                        label: {
                          show: true,
                          fontSize: '18',
                          fontWeight: 'bold'
                        }
                      },
                      labelLine: {
                        show: false
                      },
                      data: [{
                          value: 1048,
                          name: 'Search Engine'
                        },
                        {
                          value: 735,
                          name: 'Direct'
                        },
                        {
                          value: 580,
                          name: 'Email'
                        },
                        {
                          value: 484,
                          name: 'Union Ads'
                        },
                        {
                          value: 300,
                          name: 'Video Ads'
                        }
                      ]
                    }]
                  });
                });
              </script>

            </div>
          </div><!-- End Website Traffic -->

          

        </div><!-- End Right side columns -->

      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  

</body>

</html>




{% endblock %}

app_admin/templates/navadmin.html
<!-- Navbar-->

{%load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid justify-content-between">
    <!-- Left elements -->
    <div class="d-flex">
      <!-- Brand -->
      <a class="navbar-brand me-2 mb-1 d-flex align-items-center" href="#">
        <img
          src="{% static 'img/logoe.jpg' %}"
          height="69"
          loading="lazy"
          style="margin-top: 2px;"
        />
      </a>
      <a class="navbar-brand" href="{% url 'home' %}">Acceuil</a>
      <a class="navbar-brand" href="{% url 'my-article'%}">Mes articles</a>
      

      <!-- Search form -->
     
    </div>
    <!-- Left elements -->

    
    <!-- Center elements -->

    <!-- Right elements -->
    <ul class="navbar-nav flex-row">
      <li class="nav-item me-3 me-lg-1">
        <span class="nav-link d-sm-flex align-items-sm-center" href="#">
          <img
            src="https://mdbcdn.b-cdn.net/img/new/avatars/1.webp"
            class="rounded-circle"
            height="22"
            alt="Black and White Portrait of a Man"
            loading="lazy"
          />
          {% if user.is_authenticated %}
          <strong class="d-none d-sm-block ms-1 p-1">{{user.username}}</strong>
          {% endif %}
        </span>
      </li>
      </li>
      <li class="nav-item dropdown me-3 me-lg-1">
       
        
      <li class="nav-item dropdown me-3 me-lg-1">
      
        <ul class="navbar-nav my-lg-0 ml-auto">

          <div id="google_translate_element"></div>
          
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-muted  " href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  
                 <i class="fas fa-user"> </a></i>
              <div class="dropdown-menu dropdown-menu-right animated zoomIn">
                  <ul class="dropdown-user">
                    {% if user.is_authenticated %}
                      <a href="{% url 'logout1' %}"><i class="fa fa-power-off"></i> deconnexion</a>
                    {% endif %}  
                  </ul>
              </div>
          </li>
      </ul>
      </li>
    </ul>
    <!-- Right elements -->
  </div>
</nav>
<!-- Navbar -->




    
    